# Lesson 9: Exploratory Data Analysis

In [1]:
import pandas as pd
from scipy import stats

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/juanklopper/TutorialData/main/heart_failure.csv')
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,hypertension,platelets,serum_creatinine,serum_sodium,sex,smoking,time,death
0,75.0,No,582,No,20,Yes,265000.00,1.9,130,Male,No,4,Yes
1,55.0,No,7861,No,38,No,263358.03,1.1,136,Male,No,6,Yes
2,65.0,No,146,No,20,No,162000.00,1.3,129,Male,Yes,7,Yes
3,50.0,Yes,111,No,20,No,210000.00,1.9,137,Male,No,7,Yes
4,65.0,Yes,160,Yes,20,No,327000.00,2.7,116,Female,No,8,Yes

In [3]:
df.shape

(299, 13)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299 entries, 0 to 298
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       299 non-null    float64
 1   anaemia                   299 non-null    object
 2   creatinine_phosphokinase  299 non-null    int64
 3   diabetes                  299 non-null    object
 4   ejection_fraction         299 non-null    int64
 5   hypertension              299 non-null    object
 6   platelets                 299 non-null    float64
 7   serum_creatinine          299 non-null    float64
 8   serum_sodium              299 non-null    int64
 9   sex                       299 non-null    object
 10  smoking                   299 non-null    object
 11  time                      299 non-null    int64
 12  death                     299 non-null    object
dtypes: float64(3), int64(4), object(6)
memory usage: 30.5+ KB

## Tasks

### Task 1: Anaemia Analysis

In [5]:
df['anaemia'].unique()

array(['No', 'Yes'], dtype=object)

In [6]:
df['anaemia'].value_counts()

anaemia
No     170
Yes    129
Name: count, dtype: int64

In [7]:
df['anaemia'].value_counts(normalize=True)

anaemia
No     0.568562
Yes    0.431438
Name: proportion, dtype: float64

### Task 2: Diabetes Analysis

In [8]:
df['diabetes'].unique()

array(['No', 'Yes'], dtype=object)

In [9]:
df['diabetes'].value_counts()

diabetes
No     174
Yes    125
Name: count, dtype: int64

In [10]:
df['diabetes'].value_counts(normalize=True)

diabetes
No     0.58194
Yes    0.41806
Name: proportion, dtype: float64

### Task 3: Anemia vs Diabetes

In [11]:
df.groupby('diabetes').anaemia.value_counts()

diabetes  anaemia
No        No         98
          Yes        76
Yes       No         72
          Yes        53
Name: count, dtype: int64

In [12]:
df.groupby('diabetes').anaemia.value_counts(normalize=True) * 100

diabetes  anaemia
No        No         56.321839
          Yes        43.678161
Yes       No         57.600000
          Yes        42.400000
Name: proportion, dtype: float64

### Task 4: Crosstab (Diabetes Vs Anaemia)

In [13]:
pd.crosstab(df.diabetes, df.anaemia)

anaemia   No  Yes
diabetes
No        98   76
Yes       72   53

In [14]:
pd.crosstab(df.diabetes, df.anaemia, normalize=True) * 100

anaemia          No        Yes
diabetes
No        32.775920  25.418060
Yes       24.080268  17.725753

### Task 5: Anaemia Vs Death

In [15]:
pd.crosstab(df.death, df.anaemia, normalize=True) * 100

anaemia         No        Yes
death
No       40.133779  27.759197
Yes      16.722408  15.384615

### Task 6: Mean Age

In [16]:
df.age.mean()

np.float64(60.83389297658862)

In [17]:
df.groupby('death').age.mean()

death
No     58.761906
Yes    65.215281
Name: age, dtype: float64

### Task 7: Median Ejection Fraction

In [18]:
df.groupby('anaemia')['ejection_fraction'].median()

anaemia
No     38.0
Yes    38.0
Name: ejection_fraction, dtype: float64

### Task 8: Dispersion Measures

In [19]:
df.age.min()

40.0

In [20]:
df.age.max()

95.0

In [21]:
df.age.max() - df.age.min()

55.0

In [22]:
df.age.var(ddof=1)

141.48648290797084

In [23]:
df.age.std(ddof=1)

11.894809074044478

In [24]:
stats.iqr(df.age)

np.float64(19.0)

### Task 9: Variance by Anaemia

In [25]:
df.groupby('anaemia').age.var(ddof=1)

anaemia
No     141.763348
Yes    139.675064
Name: age, dtype: float64

### Task 10: Correlation

In [26]:
df.age.corr(df['ejection_fraction'])

np.float64(0.06009836323291279)

### Task 11: Describe Age

In [27]:
df.age.describe()

count    299.000000
mean      60.833893
std       11.894809
min       40.000000
25%       51.000000
50%       60.000000
75%       70.000000
max       95.000000
Name: age, dtype: float64

## Quiz Questions and Answers

In [30]:
df.head()

df['age'].mean()

df['age'].median()

df['age'].std()

df.isna().sum()

df['age'].corr(df['ejection_fraction'])

df[df['age'] > 30]

df['age'].max() - df['age'].min()

df.groupby('death')['age'].mean()

df.groupby(['death','sex']).size()

df.groupby('death')['age'].max()

pd.crosstab(df['death'], df['sex'])

pd.crosstab(df['death'], df['sex'], values=df['age'], aggfunc='mean')

sex       Female       Male
death
No     58.629113  58.833333
Yes    62.176471  66.881726